Vagrant.configure("2") do |conf|
    conf.vm.box = "bento/debian-12"


    conf.vm.define "mfadilS" do |server|
        server.vm.hostname = "mfadilS"
        server.vm.network "private_network", ip: "192.168.56.110"
        
        server.vm.provider "virtualbox" do |vb|
            vb.name = "mfadilS"
            vb.memory = "2048"
            vb.cpus = 1
        end
        server.vm.provision "shell", path: "scripts/setup.sh"
    end

end
