Vagrant.configure("2") do |config|
	config.vm.box = "bento/ubuntu-20.04"

	# =========================================
	# Machine 1: Server (Controller Mode)
	# =========================================
	config.vm.define "mfadilS" do |server|
		server.vm.hostname = "mfadilS"
		server.vm.network "private_network", ip: "192.168.56.110"

		server.vm.provider "virtualbox" do |vb|
			vb.name = "mfadilS_p2"
			vb.memory = "1024"
			vb.cpus = 1
		end

		# Install curl, then install K3s in Server/Controller mode
		server.vm.provision "shell", inline: <<-SHELL
			export INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --node-ip 192.168.56.110 --bind-address 192.168.56.110"
			curl -sfL https://get.k3s.io | sh -
		SHELL
	end
end