Vagrant.configure("2") do |conf|
    # conf.vm.box = "bento/debian-12"
    conf.vm.box = "bento/debian-12"
    conf.vm.box_version = "202309.08.0"

    conf.vm.define "mfadilS" do |server|
        server.vm.hostname = "mfadilS"
        server.vm.network "private_network", ip: "192.168.56.110"
        
        server.vm.synced_folder "shared/", "/vagrant/shared"
        server.vm.provider "VirtualBox" do |vb|
            vb.name = "mfadilS"
            vb.memory = "1024"
            vb.cpus = 1
        end 
        server.vm.provision "shell", path: "scripts/server.sh"
    end
    conf.vm.define "mfadilSW" do |agent|
        agent.vm.hostname = "mfadilSW"
        agent.vm.network "private_network", ip: "192.168.56.111"

        agent.vm.synced_folder "shared/", "/vagrant/shared"
        agent.vm.provider "VirtualBox" do |vb|
            vb.name = "mfadilSW"
            vb.memory = "1024"
            vb.cpus = 1
        end
        agent.vm.provision "shell", path: "scripts/agent.sh"
    end

  
end
