Vagrant.configure("2") do |config|
	config.vm.box = "bento/ubuntu-20.04"

	# =========================================
	# Machine 1: Server (Controller Mode)
	# =========================================
	config.vm.define "mfadilS" do |server|
		server.vm.hostname = "mfadilS"
		server.vm.network "private_network", ip: "192.168.56.110"

		server.vm.provider "virtualbox" do |vb|
			vb.name = "mfadilS"
			vb.memory = "1024"
			vb.cpus = 1
		end

		# install K3s in Server/Controller mode with kubectl
		server.vm.provision "shell", inline: <<-SHELL
			export K3S_TOKEN="iot-secret-token"
			export INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --node-ip 192.168.56.110 --bind-address 192.168.56.110"
			curl -sfL https://get.k3s.io | sh -
		SHELL
	end

	# =========================================
	# Machine 2: Server Worker(Agent Mode)
	# =========================================

	config.vm.define "mfadilSW" do |worker|
		worker.vm.hostname = "mfadilSW"
		worker.vm.network "private_network", ip: "192.168.56.111"

		worker.vm.provider "virtualbox" do |vb|
		  vb.name = "mfadilSW"
		  vb.memory = "1024"
		  vb.cpus = 1
		end

		# Install K3s in Agent/Worker mode and connect it to the Server
		worker.vm.provision "shell", inline: <<-SHELL
		  sleep 30
		  export K3S_URL="https://192.168.56.110:6443"
		  export K3S_TOKEN="iot-secret-token"
		  export INSTALL_K3S_EXEC="agent --node-ip 192.168.56.111"
		  curl -sfL https://get.k3s.io | sh -
		SHELL
	  end
end